import {
  VipBadgeId,
  VipChatBubbleId,
  VipChatBubbleItem,
  VipFrameId,
  VipFrameItem,
  VipPackage,
  VipSubscriptionState,
} from '../types';

export const DEFAULT_VIP_STATE: VipSubscriptionState = {
  isActive: false,
  tier: 'vip_gold',
  passType: '30_days',
  expiresAt: null,
  purchasedAt: 0,
  activeFrameId: 'none',
  activeChatBubbleId: 'classic',
  activeBadgeId: 'vip_crown',
  unlockedFrames: ['none'],
  unlockedChatBubbles: ['classic'],
  unlockedBadges: ['vip_crown'],
  autoRenew: false,
};

export const VIP_PACKAGES: VipPackage[] = [
  {
    id: '7_days',
    tier: 'vip_silver',
    nameBn: '৭ দিনের ট্রায়াল ভিআইপি পাস',
    nameEn: '7-Day Trial VIP Pass',
    durationDays: 7,
    durationLabelBn: '৭ দিন মেয়াদ',
    originalDiamondPrice: 50,
    diamondPrice: 35,
    badgeBn: 'শুরু করার জন্য',
    xpBoosterPercent: 15,
    unlockedFrames: ['vip_gold_dragon'],
    unlockedChatBubbles: ['vip_gold_royal'],
    unlockedBadges: ['vip_gold'],
    perksBn: [
      'গোল্ডেন ড্রাগন স্পেশাল প্রোফাইল ফ্রেম',
      'রয়্যাল গোল্ডেন চ্যাট বাবল অ্যাক্সেস',
      'গোল্ড স্টার ভিআইপি ব্যাজ',
      'প্রতি খেলায় +১৫% অতিরিক্ত XP বোনাস',
      'লাইভ অডিও ও আড্ডা বোর্ডে ভিআইপি হাইলাইট',
    ],
  },
  {
    id: '30_days',
    tier: 'vip_gold',
    nameBn: '৩০ দিনের গোল্ড ভিআইপি পাস',
    nameEn: '30-Day Gold VIP Pass',
    durationDays: 30,
    durationLabelBn: '৩০ দিন মেয়াদ',
    originalDiamondPrice: 150,
    diamondPrice: 99,
    badgeBn: 'সর্বাধিক জনপ্রিয় 🔥',
    xpBoosterPercent: 25,
    isPopular: true,
    unlockedFrames: ['vip_gold_dragon', 'vip_diamond_crown', 'vip_neon_cyber'],
    unlockedChatBubbles: ['vip_gold_royal', 'vip_neon_violet', 'vip_cyber_matrix'],
    unlockedBadges: ['vip_gold', 'vip_crown'],
    perksBn: [
      '৩টি প্রিমিয়াম ফ্রেম (ড্রাগন, ডায়মন্ড ক্রাউন, সাইবার)',
      '৩টি লাক্সারি চ্যাট বাবল (গোল্ডেন, নিয়ন, সাইবার)',
      'রয়্যাল ক্রাউন ভিআইপি ব্যাজ (নামের পাশে ঝলমলে)',
      'প্রতি খেলায় +২৫% অতিরিক্ত XP বোনাস',
      '১০ জনের লাইভ আড্ডা বোর্ডে স্পেশাল গোল্ডেন সিট',
      'দৈনিক ফ্রি স্পিন ও টুর্নামেন্টে ভিআইপি সিডিং',
    ],
  },
  {
    id: '90_days',
    tier: 'vip_diamond',
    nameBn: '৯০ দিনের সিজন সুপার ভিআইপি',
    nameEn: '90-Day Super Season VIP',
    durationDays: 90,
    durationLabelBn: '৩ মাস (৯০ দিন)',
    originalDiamondPrice: 350,
    diamondPrice: 220,
    badgeBn: 'বেস্ট ভ্যালু 💎',
    xpBoosterPercent: 35,
    isBestValue: true,
    unlockedFrames: [
      'vip_gold_dragon',
      'vip_diamond_crown',
      'vip_neon_cyber',
      'vip_flame_phoenix',
      'vip_galaxy_star',
    ],
    unlockedChatBubbles: [
      'vip_gold_royal',
      'vip_neon_violet',
      'vip_cyber_matrix',
      'vip_dragon_fire',
      'vip_diamond_glimmer',
    ],
    unlockedBadges: ['vip_gold', 'vip_crown', 'vip_diamond'],
    perksBn: [
      '৫টি এক্সক্লুসিভ ফ্রেম (ফিনিক্স ও গ্যালাক্সি সহ)',
      'সকল ৫টি কাস্টম অ্যানিমেটেড চ্যাট বাবল',
      'ডায়মন্ড কিং ভিআইপি ব্যাজ',
      'প্রতি খেলায় +৩৫% অতিরিক্ত XP বোনাস',
      'ভিআইপি রুমে ফ্রেন্ডলি ম্যাচ হোস্টিংয়ে অগ্রাধিকার',
      'ভিআইপি কাস্টমার সাপোর্ট হটলাইন অ্যাক্সেস',
    ],
  },
  {
    id: 'lifetime',
    tier: 'vip_royal',
    nameBn: 'আজীবন এলিট রয়্যাল ভিআইপি পাস',
    nameEn: 'Lifetime Elite Royal VIP',
    durationDays: 0,
    durationLabelBn: 'স্থায়ী আজীবন মেয়াদ 👑',
    originalDiamondPrice: 800,
    diamondPrice: 480,
    badgeBn: 'কিংডম অফ জয় 👑',
    xpBoosterPercent: 50,
    unlockedFrames: [
      'vip_gold_dragon',
      'vip_diamond_crown',
      'vip_neon_cyber',
      'vip_flame_phoenix',
      'vip_galaxy_star',
      'vip_royal_emperor',
    ],
    unlockedChatBubbles: [
      'vip_gold_royal',
      'vip_neon_violet',
      'vip_dragon_fire',
      'vip_cyber_matrix',
      'vip_diamond_glimmer',
    ],
    unlockedBadges: ['vip_gold', 'vip_crown', 'vip_diamond', 'vip_flame'],
    perksBn: [
      'আজীবন মেয়াদ — কখনো রিনিউ বা মেয়াদ শেষ হবে না',
      'রয়্যাল এম্পেরর গোল্ড ফ্রেম ও ফিনিক্স ব্যাজ আনলক',
      'প্রতি ম্যাচে +৫০% সর্বোচ্চ XP বোনাস',
      'গোল্ডেন নেমপ্লেট ও এক্সক্লুসিভ লাইভ এন্ট্রি সাউন্ড',
      'ভবিষ্যতে আসা সকল নতুন ভিআইপি ফ্রেম স্বয়ংক্রিয় আনলক',
    ],
  },
];

export const VIP_FRAMES: VipFrameItem[] = [
  {
    id: 'none',
    nameBn: 'স্ট্যান্ডার্ড ফ্রেম',
    descriptionBn: 'কোনো অতিরিক্ত ফ্রেম ছাড়া সাধারণ রূপ',
    minTier: 'vip_silver',
    previewGradient: 'from-slate-400 to-slate-600',
    icon: '⭕',
    glowColor: 'rgba(148, 163, 184, 0.4)',
  },
  {
    id: 'vip_gold_dragon',
    nameBn: 'গোল্ডেন ড্রাগন ফ্রেম',
    descriptionBn: 'শাহী সোনার কারুকাজ ও ড্রাগন স্কেলের দ্যুতি',
    minTier: 'vip_silver',
    previewGradient: 'from-amber-400 via-yellow-300 to-amber-600',
    icon: '🐉',
    glowColor: 'rgba(245, 158, 11, 0.6)',
  },
  {
    id: 'vip_diamond_crown',
    nameBn: 'ডায়মন্ড ক্রাউন ফ্রেম',
    descriptionBn: 'উজ্জ্বল স্ফটিক নীল হীরা ও রাজকীয় মুকুট',
    minTier: 'vip_gold',
    previewGradient: 'from-cyan-400 via-sky-300 to-blue-600',
    icon: '👑',
    glowColor: 'rgba(6, 182, 212, 0.6)',
  },
  {
    id: 'vip_neon_cyber',
    nameBn: 'সাইবার নিয়ন পালস ফ্রেম',
    descriptionBn: 'ফিউচারিস্টিক নিয়ন সাইবার সার্কিট পালস',
    minTier: 'vip_gold',
    previewGradient: 'from-fuchsia-500 via-purple-400 to-cyan-400',
    icon: '⚡',
    glowColor: 'rgba(217, 70, 239, 0.6)',
  },
  {
    id: 'vip_flame_phoenix',
    nameBn: 'ফিনিক্স ফায়ার রিং',
    descriptionBn: 'উত্তাল লাল-কমলা ফিনিক্সের অগ্নি বলয়',
    minTier: 'vip_diamond',
    previewGradient: 'from-rose-500 via-orange-500 to-amber-400',
    icon: '🔥',
    glowColor: 'rgba(244, 63, 94, 0.6)',
  },
  {
    id: 'vip_galaxy_star',
    nameBn: 'গ্যালাক্সি কসমিক ফ্রেম',
    descriptionBn: 'মহাকাশের নীহারিকা ও ঘূর্ণায়মান সোনালী তারা',
    minTier: 'vip_diamond',
    previewGradient: 'from-indigo-600 via-purple-500 to-pink-500',
    icon: '🌌',
    glowColor: 'rgba(99, 102, 241, 0.6)',
  },
  {
    id: 'vip_royal_emperor',
    nameBn: 'রয়্যাল এম্পেরর গোল্ড',
    descriptionBn: 'রোমান বাদশাহী গোল্ডেন লরেল পুষ্পমালা ও রাজমুকুট',
    minTier: 'vip_royal',
    previewGradient: 'from-amber-300 via-yellow-200 to-amber-700',
    icon: '⚜️',
    glowColor: 'rgba(251, 191, 36, 0.8)',
  },
];

export const VIP_CHAT_BUBBLES: VipChatBubbleItem[] = [
  {
    id: 'classic',
    nameBn: 'ডিফল্ট সাধারণ বাবল',
    descriptionBn: 'ক্লাসিক সাধারণ মেসেজ বাবল',
    minTier: 'vip_silver',
    themeStyle: {
      bubbleBg: 'bg-white',
      bubbleBorder: 'border-slate-200',
      textColor: 'text-slate-900',
      senderColor: 'text-slate-700',
      accentGlow: 'shadow-sm',
      badgeIcon: '💬',
    },
  },
  {
    id: 'vip_gold_royal',
    nameBn: 'রয়্যাল গোল্ডেন বাবল',
    descriptionBn: 'সোনালী কারুকাজ ও রাজকীয় মুকুট স্ট্যাম্প',
    minTier: 'vip_silver',
    themeStyle: {
      bubbleBg: 'bg-gradient-to-r from-amber-950/90 via-amber-900/90 to-yellow-950/90 text-amber-50',
      bubbleBorder: 'border-amber-400/80 shadow-amber-500/20',
      textColor: 'text-amber-100',
      senderColor: 'text-amber-300 font-black',
      accentGlow: 'shadow-md shadow-amber-900/40',
      badgeIcon: '👑',
    },
  },
  {
    id: 'vip_neon_violet',
    nameBn: 'সাইবার নিয়ন বাবল',
    descriptionBn: 'ডার্ক অর্বিট ও ইলেকট্রিক সায়ান-ভায়োলেট গ্লো',
    minTier: 'vip_gold',
    themeStyle: {
      bubbleBg: 'bg-gradient-to-r from-slate-950 via-purple-950 to-indigo-950 text-fuchsia-100',
      bubbleBorder: 'border-fuchsia-400/80 shadow-fuchsia-500/25',
      textColor: 'text-fuchsia-100',
      senderColor: 'text-cyan-300 font-black',
      accentGlow: 'shadow-md shadow-purple-950/50',
      badgeIcon: '⚡',
    },
  },
  {
    id: 'vip_dragon_fire',
    nameBn: 'ড্রাগন ফায়ার বাবল',
    descriptionBn: 'উত্তপ্ত রুবি রেড ব্যাকগ্রাউন্ড ও ড্রাগন ফ্লেয়ার',
    minTier: 'vip_diamond',
    themeStyle: {
      bubbleBg: 'bg-gradient-to-r from-rose-950 via-red-900 to-orange-950 text-rose-100',
      bubbleBorder: 'border-rose-400/80 shadow-rose-500/25',
      textColor: 'text-orange-100',
      senderColor: 'text-yellow-300 font-black',
      accentGlow: 'shadow-md shadow-red-950/50',
      badgeIcon: '🔥',
    },
  },
  {
    id: 'vip_cyber_matrix',
    nameBn: 'ম্যাট্রিক্স গ্রিড বাবল',
    descriptionBn: 'সায়েন্স-ফিকশন পান্না গ্রিন ও ডিজিটাল বর্ডার',
    minTier: 'vip_gold',
    themeStyle: {
      bubbleBg: 'bg-gradient-to-r from-slate-950 via-teal-950 to-emerald-950 text-teal-100',
      bubbleBorder: 'border-emerald-400/80 shadow-emerald-500/20',
      textColor: 'text-emerald-100',
      senderColor: 'text-teal-300 font-black',
      accentGlow: 'shadow-md shadow-teal-950/50',
      badgeIcon: '🌐',
    },
  },
  {
    id: 'vip_diamond_glimmer',
    nameBn: 'আইস ডায়মন্ড বাবল',
    descriptionBn: 'স্বচ্ছ হীরার দ্যুতি ও ক্রিস্টাল ব্লু টেক্সটাইল',
    minTier: 'vip_diamond',
    themeStyle: {
      bubbleBg: 'bg-gradient-to-r from-cyan-950/90 via-sky-950 to-blue-950 text-cyan-100',
      bubbleBorder: 'border-cyan-300 shadow-cyan-400/30',
      textColor: 'text-cyan-100',
      senderColor: 'text-sky-300 font-black',
      accentGlow: 'shadow-md shadow-sky-900/50',
      badgeIcon: '💎',
    },
  },
];

export const VIP_BADGES: {
  id: VipBadgeId;
  nameBn: string;
  badgeLabel: string;
  icon: string;
  styleClass: string;
  borderClass: string;
}[] = [
  {
    id: 'vip_crown',
    nameBn: 'রয়্যাল ক্রাউন ভিআইপি',
    badgeLabel: 'VIP CROWN',
    icon: '👑',
    styleClass: 'bg-gradient-to-r from-amber-400 via-yellow-300 to-amber-500 text-amber-950',
    borderClass: 'border-amber-600',
  },
  {
    id: 'vip_gold',
    nameBn: 'গোল্ডেন স্টার ভিআইপি',
    badgeLabel: 'GOLD VIP',
    icon: '⭐',
    styleClass: 'bg-gradient-to-r from-yellow-400 to-amber-500 text-slate-950',
    borderClass: 'border-yellow-600',
  },
  {
    id: 'vip_diamond',
    nameBn: 'ডায়মন্ড কিং ভিআইপি',
    badgeLabel: 'DIAMOND VIP',
    icon: '💎',
    styleClass: 'bg-gradient-to-r from-cyan-400 via-sky-300 to-blue-500 text-slate-950',
    borderClass: 'border-cyan-600',
  },
  {
    id: 'vip_flame',
    nameBn: 'ফিনিক্স লিজেন্ড ভিআইপি',
    badgeLabel: 'ROYAL ELITE',
    icon: '🔥',
    styleClass: 'bg-gradient-to-r from-rose-500 via-orange-400 to-amber-300 text-white',
    borderClass: 'border-rose-700',
  },
];
